#ifndef DEBUG_H
#define DEBUG_H

/* #define NO_DALI_DBG */

/* #define NO_DALI_DBG_ALLOC */
/* #define NO_DALI_DBG_MEMSTATS */
/* #define NO_DALI_DBG_FLUSH */
/* #define NO_DALI_DBG_ITEMS */
/* #define NO_DALI_DBG_ITEMSCR */
/* #define NO_DALI_DBG_DALI */
/* #define NO_DALI_DBG_LOG */
/* #define NO_DALI_DBG_LOGPHYSINFO */
/* #define NO_DALI_DBG_LOG_ALLOC */
/* #define NO_DALI_DBG_RECOVER */
/* #define NO_DALI_DBG_RECFIXDUMMY */
/* #define NO_DALI_DBG_LOCK */
/* #define NO_DALI_DBG_LOCKAUDIT */
/* #define NO_DALI_DBG_MUTEX */
/* #define NO_DALI_DBG_MUTEXAUDIT */
/* #define NO_DALI_DBG_TIMEOUT */
/* #define NO_DALI_DBG_TESTER */
/* #define NO_DALI_DBG_TORTIMESTAMP */
/* #define NO_DALI_DBG_TRANS */
/* #define NO_DALI_DBG_CLEANUP */
/* #define NO_DALI_DBG_CLEANUP1 */
/* #define NO_DALI_DBG_NOEXITCODE */
/* #define NO_DALI_DBG_CODEWORD */
/* #define NO_DALI_DBG_CHECKPT */
/* #define NO_DALI_DBG_CHECKPT1 */
/* #define NO_DALI_DBG_ROOTSRV */
/* #define NO_DALI_DBG_ROOTSRV_DBX */
/* #define NO_DALI_DBG_EXTERNAL_LOCK_AUDIT */
/* #define NO_DALI_DBG_EXTERNAL_ALLOC_AUDIT */
/* #define NO_DALI_DBG_PAGE_TABLE */
/* #define NO_DALI_DBG_TTREE */
/* #define NO_DALI_DBG_TTREE1 */
/* #define NO_DALI_DBG_HASH */
/* #define NO_DALI_DBG_SHMEM */
/*
 *  WARNING: DO NOT EDIT THIS FILE BELOW THIS POINT.
 *  It is automatically generated by the debuggen command!
 *  Try changing debug.master, then make <this file> to fix it. 
 * 
 */

extern int dali_dbg_printf(char *format ...);
extern int dali_dbg_stamp(int debug_mode, char *filename, int line);

/*
 * DALI_DBG_ALLOC:
 *      Debug memory allocator (f_alloc  and f_free
 */
#if  !defined(NO_DALI_DBG_ALLOC) && !defined(NO_DALI_DBG)
extern int dali_dbg_alloc;
#define DALI_DBG_ALLOC_CODE(stmt)  {if(dali_dbg_alloc) {stmt}}
#define DALI_DBG_ALLOC_ST_CODE(stmt)  {if(dali_dbg_alloc) { \
        dali_dbg_stamp( 0, __FILE__, __LINE__); {stmt} }}
#define DALI_DBG_ALLOC_PRINTF(printfargs) \
        { DALI_DBG_ALLOC_CODE(dali_dbg_printf printfargs ;)}
#define DALI_DBG_ALLOC_ST_PRINTF(printfargs) \
        { DALI_DBG_ALLOC_ST_CODE( dali_dbg_printf printfargs ;)}
#define DALI_DBG_ALLOC_VAR(decl)  decl
#define DALI_DBG_ALLOC(printfargs) DALI_DBG_ALLOC_ST_PRINTF(printfargs)
#else
#define DALI_DBG_ALLOC_CODE(stmt)   ;
#define DALI_DBG_ALLOC_ST_CODE(stmt)   ;
#define DALI_DBG_ALLOC_PRINTF(printfargs)   ;
#define DALI_DBG_ALLOC_ST_PRINTF(printfargs)   ;
#define DALI_DBG_ALLOC_VAR(decl)   
#define DALI_DBG_ALLOC(printfargs) ;

#endif

/*
 * DALI_DBG_MEMSTATS:
 *      Gather memory usage statistics per transactio
 */
#if  !defined(NO_DALI_DBG_MEMSTATS) && !defined(NO_DALI_DBG)
extern int dali_dbg_memstats;
#define DALI_DBG_MEMSTATS_CODE(stmt)  {if(dali_dbg_memstats) {stmt}}
#define DALI_DBG_MEMSTATS_ST_CODE(stmt)  {if(dali_dbg_memstats) { \
        dali_dbg_stamp( 1, __FILE__, __LINE__); {stmt} }}
#define DALI_DBG_MEMSTATS_PRINTF(printfargs) \
        { DALI_DBG_MEMSTATS_CODE(dali_dbg_printf printfargs ;)}
#define DALI_DBG_MEMSTATS_ST_PRINTF(printfargs) \
        { DALI_DBG_MEMSTATS_ST_CODE( dali_dbg_printf printfargs ;)}
#define DALI_DBG_MEMSTATS_VAR(decl)  decl
#define DALI_DBG_MEMSTATS(printfargs) DALI_DBG_MEMSTATS_ST_PRINTF(printfargs)
#else
#define DALI_DBG_MEMSTATS_CODE(stmt)   ;
#define DALI_DBG_MEMSTATS_ST_CODE(stmt)   ;
#define DALI_DBG_MEMSTATS_PRINTF(printfargs)   ;
#define DALI_DBG_MEMSTATS_ST_PRINTF(printfargs)   ;
#define DALI_DBG_MEMSTATS_VAR(decl)   
#define DALI_DBG_MEMSTATS(printfargs) ;

#endif

/*
 * DALI_DBG_FLUSH:
 *      Note when things get committed
 */
#if  !defined(NO_DALI_DBG_FLUSH) && !defined(NO_DALI_DBG)
extern int dali_dbg_flush;
#define DALI_DBG_FLUSH_CODE(stmt)  {if(dali_dbg_flush) {stmt}}
#define DALI_DBG_FLUSH_ST_CODE(stmt)  {if(dali_dbg_flush) { \
        dali_dbg_stamp( 2, __FILE__, __LINE__); {stmt} }}
#define DALI_DBG_FLUSH_PRINTF(printfargs) \
        { DALI_DBG_FLUSH_CODE(dali_dbg_printf printfargs ;)}
#define DALI_DBG_FLUSH_ST_PRINTF(printfargs) \
        { DALI_DBG_FLUSH_ST_CODE( dali_dbg_printf printfargs ;)}
#define DALI_DBG_FLUSH_VAR(decl)  decl
#define DALI_DBG_FLUSH(printfargs) DALI_DBG_FLUSH_ST_PRINTF(printfargs)
#else
#define DALI_DBG_FLUSH_CODE(stmt)   ;
#define DALI_DBG_FLUSH_ST_CODE(stmt)   ;
#define DALI_DBG_FLUSH_PRINTF(printfargs)   ;
#define DALI_DBG_FLUSH_ST_PRINTF(printfargs)   ;
#define DALI_DBG_FLUSH_VAR(decl)   
#define DALI_DBG_FLUSH(printfargs) ;

#endif

/*
 * DALI_DBG_ITEMS:
 *      Item Manager.  Print outs during create/get/put item
 */
#if  !defined(NO_DALI_DBG_ITEMS) && !defined(NO_DALI_DBG)
extern int dali_dbg_items;
#define DALI_DBG_ITEMS_CODE(stmt)  {if(dali_dbg_items) {stmt}}
#define DALI_DBG_ITEMS_ST_CODE(stmt)  {if(dali_dbg_items) { \
        dali_dbg_stamp( 3, __FILE__, __LINE__); {stmt} }}
#define DALI_DBG_ITEMS_PRINTF(printfargs) \
        { DALI_DBG_ITEMS_CODE(dali_dbg_printf printfargs ;)}
#define DALI_DBG_ITEMS_ST_PRINTF(printfargs) \
        { DALI_DBG_ITEMS_ST_CODE( dali_dbg_printf printfargs ;)}
#define DALI_DBG_ITEMS_VAR(decl)  decl
#define DALI_DBG_ITEMS(printfargs) DALI_DBG_ITEMS_ST_PRINTF(printfargs)
#else
#define DALI_DBG_ITEMS_CODE(stmt)   ;
#define DALI_DBG_ITEMS_ST_CODE(stmt)   ;
#define DALI_DBG_ITEMS_PRINTF(printfargs)   ;
#define DALI_DBG_ITEMS_ST_PRINTF(printfargs)   ;
#define DALI_DBG_ITEMS_VAR(decl)   
#define DALI_DBG_ITEMS(printfargs) ;

#endif

/*
 * DALI_DBG_ITEMSCR:
 *      Print creates to help map items to DaliPtrs. (not impl
 */
#if  !defined(NO_DALI_DBG_ITEMSCR) && !defined(NO_DALI_DBG)
extern int dali_dbg_itemscr;
#define DALI_DBG_ITEMSCR_CODE(stmt)  {if(dali_dbg_itemscr) {stmt}}
#define DALI_DBG_ITEMSCR_ST_CODE(stmt)  {if(dali_dbg_itemscr) { \
        dali_dbg_stamp( 4, __FILE__, __LINE__); {stmt} }}
#define DALI_DBG_ITEMSCR_PRINTF(printfargs) \
        { DALI_DBG_ITEMSCR_CODE(dali_dbg_printf printfargs ;)}
#define DALI_DBG_ITEMSCR_ST_PRINTF(printfargs) \
        { DALI_DBG_ITEMSCR_ST_CODE( dali_dbg_printf printfargs ;)}
#define DALI_DBG_ITEMSCR_VAR(decl)  decl
#define DALI_DBG_ITEMSCR(printfargs) DALI_DBG_ITEMSCR_ST_PRINTF(printfargs)
#else
#define DALI_DBG_ITEMSCR_CODE(stmt)   ;
#define DALI_DBG_ITEMSCR_ST_CODE(stmt)   ;
#define DALI_DBG_ITEMSCR_PRINTF(printfargs)   ;
#define DALI_DBG_ITEMSCR_ST_PRINTF(printfargs)   ;
#define DALI_DBG_ITEMSCR_VAR(decl)   
#define DALI_DBG_ITEMSCR(printfargs) ;

#endif

/*
 * DALI_DBG_DALI:
 *      A Generic Dali Debug class
 */
#if  !defined(NO_DALI_DBG_DALI) && !defined(NO_DALI_DBG)
extern int dali_dbg_dali;
#define DALI_DBG_DALI_CODE(stmt)  {if(dali_dbg_dali) {stmt}}
#define DALI_DBG_DALI_ST_CODE(stmt)  {if(dali_dbg_dali) { \
        dali_dbg_stamp( 5, __FILE__, __LINE__); {stmt} }}
#define DALI_DBG_DALI_PRINTF(printfargs) \
        { DALI_DBG_DALI_CODE(dali_dbg_printf printfargs ;)}
#define DALI_DBG_DALI_ST_PRINTF(printfargs) \
        { DALI_DBG_DALI_ST_CODE( dali_dbg_printf printfargs ;)}
#define DALI_DBG_DALI_VAR(decl)  decl
#define DALI_DBG_DALI(printfargs) DALI_DBG_DALI_ST_PRINTF(printfargs)
#else
#define DALI_DBG_DALI_CODE(stmt)   ;
#define DALI_DBG_DALI_ST_CODE(stmt)   ;
#define DALI_DBG_DALI_PRINTF(printfargs)   ;
#define DALI_DBG_DALI_ST_PRINTF(printfargs)   ;
#define DALI_DBG_DALI_VAR(decl)   
#define DALI_DBG_DALI(printfargs) ;

#endif

/*
 * DALI_DBG_LOG:
 *      Logging Code debug
 */
#if  !defined(NO_DALI_DBG_LOG) && !defined(NO_DALI_DBG)
extern int dali_dbg_log;
#define DALI_DBG_LOG_CODE(stmt)  {if(dali_dbg_log) {stmt}}
#define DALI_DBG_LOG_ST_CODE(stmt)  {if(dali_dbg_log) { \
        dali_dbg_stamp( 6, __FILE__, __LINE__); {stmt} }}
#define DALI_DBG_LOG_PRINTF(printfargs) \
        { DALI_DBG_LOG_CODE(dali_dbg_printf printfargs ;)}
#define DALI_DBG_LOG_ST_PRINTF(printfargs) \
        { DALI_DBG_LOG_ST_CODE( dali_dbg_printf printfargs ;)}
#define DALI_DBG_LOG_VAR(decl)  decl
#define DALI_DBG_LOG(printfargs) DALI_DBG_LOG_ST_PRINTF(printfargs)
#else
#define DALI_DBG_LOG_CODE(stmt)   ;
#define DALI_DBG_LOG_ST_CODE(stmt)   ;
#define DALI_DBG_LOG_PRINTF(printfargs)   ;
#define DALI_DBG_LOG_ST_PRINTF(printfargs)   ;
#define DALI_DBG_LOG_VAR(decl)   
#define DALI_DBG_LOG(printfargs) ;

#endif

/*
 * DALI_DBG_LOGPHYSINFO:
 *      Print detail of physical log records
 */
#if  !defined(NO_DALI_DBG_LOGPHYSINFO) && !defined(NO_DALI_DBG)
extern int dali_dbg_logphysinfo;
#define DALI_DBG_LOGPHYSINFO_CODE(stmt)  {if(dali_dbg_logphysinfo) {stmt}}
#define DALI_DBG_LOGPHYSINFO_ST_CODE(stmt)  {if(dali_dbg_logphysinfo) { \
        dali_dbg_stamp( 7, __FILE__, __LINE__); {stmt} }}
#define DALI_DBG_LOGPHYSINFO_PRINTF(printfargs) \
        { DALI_DBG_LOGPHYSINFO_CODE(dali_dbg_printf printfargs ;)}
#define DALI_DBG_LOGPHYSINFO_ST_PRINTF(printfargs) \
        { DALI_DBG_LOGPHYSINFO_ST_CODE( dali_dbg_printf printfargs ;)}
#define DALI_DBG_LOGPHYSINFO_VAR(decl)  decl
#define DALI_DBG_LOGPHYSINFO(printfargs) DALI_DBG_LOGPHYSINFO_ST_PRINTF(printfargs)
#else
#define DALI_DBG_LOGPHYSINFO_CODE(stmt)   ;
#define DALI_DBG_LOGPHYSINFO_ST_CODE(stmt)   ;
#define DALI_DBG_LOGPHYSINFO_PRINTF(printfargs)   ;
#define DALI_DBG_LOGPHYSINFO_ST_PRINTF(printfargs)   ;
#define DALI_DBG_LOGPHYSINFO_VAR(decl)   
#define DALI_DBG_LOGPHYSINFO(printfargs) ;

#endif

/*
 * DALI_DBG_LOG_ALLOC:
 *      Private Log Allocator
 */
#if  !defined(NO_DALI_DBG_LOG_ALLOC) && !defined(NO_DALI_DBG)
extern int dali_dbg_log_alloc;
#define DALI_DBG_LOG_ALLOC_CODE(stmt)  {if(dali_dbg_log_alloc) {stmt}}
#define DALI_DBG_LOG_ALLOC_ST_CODE(stmt)  {if(dali_dbg_log_alloc) { \
        dali_dbg_stamp( 8, __FILE__, __LINE__); {stmt} }}
#define DALI_DBG_LOG_ALLOC_PRINTF(printfargs) \
        { DALI_DBG_LOG_ALLOC_CODE(dali_dbg_printf printfargs ;)}
#define DALI_DBG_LOG_ALLOC_ST_PRINTF(printfargs) \
        { DALI_DBG_LOG_ALLOC_ST_CODE( dali_dbg_printf printfargs ;)}
#define DALI_DBG_LOG_ALLOC_VAR(decl)  decl
#define DALI_DBG_LOG_ALLOC(printfargs) DALI_DBG_LOG_ALLOC_ST_PRINTF(printfargs)
#else
#define DALI_DBG_LOG_ALLOC_CODE(stmt)   ;
#define DALI_DBG_LOG_ALLOC_ST_CODE(stmt)   ;
#define DALI_DBG_LOG_ALLOC_PRINTF(printfargs)   ;
#define DALI_DBG_LOG_ALLOC_ST_PRINTF(printfargs)   ;
#define DALI_DBG_LOG_ALLOC_VAR(decl)   
#define DALI_DBG_LOG_ALLOC(printfargs) ;

#endif

/*
 * DALI_DBG_RECOVER:
 *      Debug Recover
 */
#if  !defined(NO_DALI_DBG_RECOVER) && !defined(NO_DALI_DBG)
extern int dali_dbg_recover;
#define DALI_DBG_RECOVER_CODE(stmt)  {if(dali_dbg_recover) {stmt}}
#define DALI_DBG_RECOVER_ST_CODE(stmt)  {if(dali_dbg_recover) { \
        dali_dbg_stamp( 9, __FILE__, __LINE__); {stmt} }}
#define DALI_DBG_RECOVER_PRINTF(printfargs) \
        { DALI_DBG_RECOVER_CODE(dali_dbg_printf printfargs ;)}
#define DALI_DBG_RECOVER_ST_PRINTF(printfargs) \
        { DALI_DBG_RECOVER_ST_CODE( dali_dbg_printf printfargs ;)}
#define DALI_DBG_RECOVER_VAR(decl)  decl
#define DALI_DBG_RECOVER(printfargs) DALI_DBG_RECOVER_ST_PRINTF(printfargs)
#else
#define DALI_DBG_RECOVER_CODE(stmt)   ;
#define DALI_DBG_RECOVER_ST_CODE(stmt)   ;
#define DALI_DBG_RECOVER_PRINTF(printfargs)   ;
#define DALI_DBG_RECOVER_ST_PRINTF(printfargs)   ;
#define DALI_DBG_RECOVER_VAR(decl)   
#define DALI_DBG_RECOVER(printfargs) ;

#endif

/*
 * DALI_DBG_RECFIXDUMMY:
 *      Debug fixing of dummy undo records during recover
 */
#if  !defined(NO_DALI_DBG_RECFIXDUMMY) && !defined(NO_DALI_DBG)
extern int dali_dbg_recfixdummy;
#define DALI_DBG_RECFIXDUMMY_CODE(stmt)  {if(dali_dbg_recfixdummy) {stmt}}
#define DALI_DBG_RECFIXDUMMY_ST_CODE(stmt)  {if(dali_dbg_recfixdummy) { \
        dali_dbg_stamp( 10, __FILE__, __LINE__); {stmt} }}
#define DALI_DBG_RECFIXDUMMY_PRINTF(printfargs) \
        { DALI_DBG_RECFIXDUMMY_CODE(dali_dbg_printf printfargs ;)}
#define DALI_DBG_RECFIXDUMMY_ST_PRINTF(printfargs) \
        { DALI_DBG_RECFIXDUMMY_ST_CODE( dali_dbg_printf printfargs ;)}
#define DALI_DBG_RECFIXDUMMY_VAR(decl)  decl
#define DALI_DBG_RECFIXDUMMY(printfargs) DALI_DBG_RECFIXDUMMY_ST_PRINTF(printfargs)
#else
#define DALI_DBG_RECFIXDUMMY_CODE(stmt)   ;
#define DALI_DBG_RECFIXDUMMY_ST_CODE(stmt)   ;
#define DALI_DBG_RECFIXDUMMY_PRINTF(printfargs)   ;
#define DALI_DBG_RECFIXDUMMY_ST_PRINTF(printfargs)   ;
#define DALI_DBG_RECFIXDUMMY_VAR(decl)   
#define DALI_DBG_RECFIXDUMMY(printfargs) ;

#endif

/*
 * DALI_DBG_LOCK:
 *      Locking cod
 */
#if  !defined(NO_DALI_DBG_LOCK) && !defined(NO_DALI_DBG)
extern int dali_dbg_lock;
#define DALI_DBG_LOCK_CODE(stmt)  {if(dali_dbg_lock) {stmt}}
#define DALI_DBG_LOCK_ST_CODE(stmt)  {if(dali_dbg_lock) { \
        dali_dbg_stamp( 11, __FILE__, __LINE__); {stmt} }}
#define DALI_DBG_LOCK_PRINTF(printfargs) \
        { DALI_DBG_LOCK_CODE(dali_dbg_printf printfargs ;)}
#define DALI_DBG_LOCK_ST_PRINTF(printfargs) \
        { DALI_DBG_LOCK_ST_CODE( dali_dbg_printf printfargs ;)}
#define DALI_DBG_LOCK_VAR(decl)  decl
#define DALI_DBG_LOCK(printfargs) DALI_DBG_LOCK_ST_PRINTF(printfargs)
#else
#define DALI_DBG_LOCK_CODE(stmt)   ;
#define DALI_DBG_LOCK_ST_CODE(stmt)   ;
#define DALI_DBG_LOCK_PRINTF(printfargs)   ;
#define DALI_DBG_LOCK_ST_PRINTF(printfargs)   ;
#define DALI_DBG_LOCK_VAR(decl)   
#define DALI_DBG_LOCK(printfargs) ;

#endif

/*
 * DALI_DBG_LOCKAUDIT:
 *      Silent audits in locking cod
 */
#if  !defined(NO_DALI_DBG_LOCKAUDIT) && !defined(NO_DALI_DBG)
extern int dali_dbg_lockaudit;
#define DALI_DBG_LOCKAUDIT_CODE(stmt)  {if(dali_dbg_lockaudit) {stmt}}
#define DALI_DBG_LOCKAUDIT_ST_CODE(stmt)  {if(dali_dbg_lockaudit) { \
        dali_dbg_stamp( 12, __FILE__, __LINE__); {stmt} }}
#define DALI_DBG_LOCKAUDIT_PRINTF(printfargs) \
        { DALI_DBG_LOCKAUDIT_CODE(dali_dbg_printf printfargs ;)}
#define DALI_DBG_LOCKAUDIT_ST_PRINTF(printfargs) \
        { DALI_DBG_LOCKAUDIT_ST_CODE( dali_dbg_printf printfargs ;)}
#define DALI_DBG_LOCKAUDIT_VAR(decl)  decl
#define DALI_DBG_LOCKAUDIT(printfargs) DALI_DBG_LOCKAUDIT_ST_PRINTF(printfargs)
#else
#define DALI_DBG_LOCKAUDIT_CODE(stmt)   ;
#define DALI_DBG_LOCKAUDIT_ST_CODE(stmt)   ;
#define DALI_DBG_LOCKAUDIT_PRINTF(printfargs)   ;
#define DALI_DBG_LOCKAUDIT_ST_PRINTF(printfargs)   ;
#define DALI_DBG_LOCKAUDIT_VAR(decl)   
#define DALI_DBG_LOCKAUDIT(printfargs) ;

#endif

/*
 * DALI_DBG_MUTEX:
 *      Safe Mutex cod
 */
#if  !defined(NO_DALI_DBG_MUTEX) && !defined(NO_DALI_DBG)
extern int dali_dbg_mutex;
#define DALI_DBG_MUTEX_CODE(stmt)  {if(dali_dbg_mutex) {stmt}}
#define DALI_DBG_MUTEX_ST_CODE(stmt)  {if(dali_dbg_mutex) { \
        dali_dbg_stamp( 13, __FILE__, __LINE__); {stmt} }}
#define DALI_DBG_MUTEX_PRINTF(printfargs) \
        { DALI_DBG_MUTEX_CODE(dali_dbg_printf printfargs ;)}
#define DALI_DBG_MUTEX_ST_PRINTF(printfargs) \
        { DALI_DBG_MUTEX_ST_CODE( dali_dbg_printf printfargs ;)}
#define DALI_DBG_MUTEX_VAR(decl)  decl
#define DALI_DBG_MUTEX(printfargs) DALI_DBG_MUTEX_ST_PRINTF(printfargs)
#else
#define DALI_DBG_MUTEX_CODE(stmt)   ;
#define DALI_DBG_MUTEX_ST_CODE(stmt)   ;
#define DALI_DBG_MUTEX_PRINTF(printfargs)   ;
#define DALI_DBG_MUTEX_ST_PRINTF(printfargs)   ;
#define DALI_DBG_MUTEX_VAR(decl)   
#define DALI_DBG_MUTEX(printfargs) ;

#endif

/*
 * DALI_DBG_MUTEXAUDIT:
 *      Monitoring and reporting for SafeMutex'
 */
#if  !defined(NO_DALI_DBG_MUTEXAUDIT) && !defined(NO_DALI_DBG)
extern int dali_dbg_mutexaudit;
#define DALI_DBG_MUTEXAUDIT_CODE(stmt)  {if(dali_dbg_mutexaudit) {stmt}}
#define DALI_DBG_MUTEXAUDIT_ST_CODE(stmt)  {if(dali_dbg_mutexaudit) { \
        dali_dbg_stamp( 14, __FILE__, __LINE__); {stmt} }}
#define DALI_DBG_MUTEXAUDIT_PRINTF(printfargs) \
        { DALI_DBG_MUTEXAUDIT_CODE(dali_dbg_printf printfargs ;)}
#define DALI_DBG_MUTEXAUDIT_ST_PRINTF(printfargs) \
        { DALI_DBG_MUTEXAUDIT_ST_CODE( dali_dbg_printf printfargs ;)}
#define DALI_DBG_MUTEXAUDIT_VAR(decl)  decl
#define DALI_DBG_MUTEXAUDIT(printfargs) DALI_DBG_MUTEXAUDIT_ST_PRINTF(printfargs)
#else
#define DALI_DBG_MUTEXAUDIT_CODE(stmt)   ;
#define DALI_DBG_MUTEXAUDIT_ST_CODE(stmt)   ;
#define DALI_DBG_MUTEXAUDIT_PRINTF(printfargs)   ;
#define DALI_DBG_MUTEXAUDIT_ST_PRINTF(printfargs)   ;
#define DALI_DBG_MUTEXAUDIT_VAR(decl)   
#define DALI_DBG_MUTEXAUDIT(printfargs) ;

#endif

/*
 * DALI_DBG_TIMEOUT:
 *      Mutex and Lock Timeout
 */
#if  !defined(NO_DALI_DBG_TIMEOUT) && !defined(NO_DALI_DBG)
extern int dali_dbg_timeout;
#define DALI_DBG_TIMEOUT_CODE(stmt)  {if(dali_dbg_timeout) {stmt}}
#define DALI_DBG_TIMEOUT_ST_CODE(stmt)  {if(dali_dbg_timeout) { \
        dali_dbg_stamp( 15, __FILE__, __LINE__); {stmt} }}
#define DALI_DBG_TIMEOUT_PRINTF(printfargs) \
        { DALI_DBG_TIMEOUT_CODE(dali_dbg_printf printfargs ;)}
#define DALI_DBG_TIMEOUT_ST_PRINTF(printfargs) \
        { DALI_DBG_TIMEOUT_ST_CODE( dali_dbg_printf printfargs ;)}
#define DALI_DBG_TIMEOUT_VAR(decl)  decl
#define DALI_DBG_TIMEOUT(printfargs) DALI_DBG_TIMEOUT_ST_PRINTF(printfargs)
#else
#define DALI_DBG_TIMEOUT_CODE(stmt)   ;
#define DALI_DBG_TIMEOUT_ST_CODE(stmt)   ;
#define DALI_DBG_TIMEOUT_PRINTF(printfargs)   ;
#define DALI_DBG_TIMEOUT_ST_PRINTF(printfargs)   ;
#define DALI_DBG_TIMEOUT_VAR(decl)   
#define DALI_DBG_TIMEOUT(printfargs) ;

#endif

/*
 * DALI_DBG_TESTER:
 *      Used by tests to print in same format as debug messages
 */
#if  !defined(NO_DALI_DBG_TESTER) && !defined(NO_DALI_DBG)
extern int dali_dbg_tester;
#define DALI_DBG_TESTER_CODE(stmt)  {if(dali_dbg_tester) {stmt}}
#define DALI_DBG_TESTER_ST_CODE(stmt)  {if(dali_dbg_tester) { \
        dali_dbg_stamp( 16, __FILE__, __LINE__); {stmt} }}
#define DALI_DBG_TESTER_PRINTF(printfargs) \
        { DALI_DBG_TESTER_CODE(dali_dbg_printf printfargs ;)}
#define DALI_DBG_TESTER_ST_PRINTF(printfargs) \
        { DALI_DBG_TESTER_ST_CODE( dali_dbg_printf printfargs ;)}
#define DALI_DBG_TESTER_VAR(decl)  decl
#define DALI_DBG_TESTER(printfargs) DALI_DBG_TESTER_ST_PRINTF(printfargs)
#else
#define DALI_DBG_TESTER_CODE(stmt)   ;
#define DALI_DBG_TESTER_ST_CODE(stmt)   ;
#define DALI_DBG_TESTER_PRINTF(printfargs)   ;
#define DALI_DBG_TESTER_ST_PRINTF(printfargs)   ;
#define DALI_DBG_TESTER_VAR(decl)   
#define DALI_DBG_TESTER(printfargs) ;

#endif

/*
 * DALI_DBG_TORTIMESTAMP:
 *      Display messages with times not files and line number
 */
#if  !defined(NO_DALI_DBG_TORTIMESTAMP) && !defined(NO_DALI_DBG)
extern int dali_dbg_tortimestamp;
#define DALI_DBG_TORTIMESTAMP_CODE(stmt)  {if(dali_dbg_tortimestamp) {stmt}}
#define DALI_DBG_TORTIMESTAMP_ST_CODE(stmt)  {if(dali_dbg_tortimestamp) { \
        dali_dbg_stamp( 17, __FILE__, __LINE__); {stmt} }}
#define DALI_DBG_TORTIMESTAMP_PRINTF(printfargs) \
        { DALI_DBG_TORTIMESTAMP_CODE(dali_dbg_printf printfargs ;)}
#define DALI_DBG_TORTIMESTAMP_ST_PRINTF(printfargs) \
        { DALI_DBG_TORTIMESTAMP_ST_CODE( dali_dbg_printf printfargs ;)}
#define DALI_DBG_TORTIMESTAMP_VAR(decl)  decl
#define DALI_DBG_TORTIMESTAMP(printfargs) DALI_DBG_TORTIMESTAMP_ST_PRINTF(printfargs)
#else
#define DALI_DBG_TORTIMESTAMP_CODE(stmt)   ;
#define DALI_DBG_TORTIMESTAMP_ST_CODE(stmt)   ;
#define DALI_DBG_TORTIMESTAMP_PRINTF(printfargs)   ;
#define DALI_DBG_TORTIMESTAMP_ST_PRINTF(printfargs)   ;
#define DALI_DBG_TORTIMESTAMP_VAR(decl)   
#define DALI_DBG_TORTIMESTAMP(printfargs) ;

#endif

/*
 * DALI_DBG_TRANS:
 *      Transaction lifetime
 */
#if  !defined(NO_DALI_DBG_TRANS) && !defined(NO_DALI_DBG)
extern int dali_dbg_trans;
#define DALI_DBG_TRANS_CODE(stmt)  {if(dali_dbg_trans) {stmt}}
#define DALI_DBG_TRANS_ST_CODE(stmt)  {if(dali_dbg_trans) { \
        dali_dbg_stamp( 18, __FILE__, __LINE__); {stmt} }}
#define DALI_DBG_TRANS_PRINTF(printfargs) \
        { DALI_DBG_TRANS_CODE(dali_dbg_printf printfargs ;)}
#define DALI_DBG_TRANS_ST_PRINTF(printfargs) \
        { DALI_DBG_TRANS_ST_CODE( dali_dbg_printf printfargs ;)}
#define DALI_DBG_TRANS_VAR(decl)  decl
#define DALI_DBG_TRANS(printfargs) DALI_DBG_TRANS_ST_PRINTF(printfargs)
#else
#define DALI_DBG_TRANS_CODE(stmt)   ;
#define DALI_DBG_TRANS_ST_CODE(stmt)   ;
#define DALI_DBG_TRANS_PRINTF(printfargs)   ;
#define DALI_DBG_TRANS_ST_PRINTF(printfargs)   ;
#define DALI_DBG_TRANS_VAR(decl)   
#define DALI_DBG_TRANS(printfargs) ;

#endif

/*
 * DALI_DBG_CLEANUP:
 *      Process failure cleanup code -- less detai
 */
#if  !defined(NO_DALI_DBG_CLEANUP) && !defined(NO_DALI_DBG)
extern int dali_dbg_cleanup;
#define DALI_DBG_CLEANUP_CODE(stmt)  {if(dali_dbg_cleanup) {stmt}}
#define DALI_DBG_CLEANUP_ST_CODE(stmt)  {if(dali_dbg_cleanup) { \
        dali_dbg_stamp( 19, __FILE__, __LINE__); {stmt} }}
#define DALI_DBG_CLEANUP_PRINTF(printfargs) \
        { DALI_DBG_CLEANUP_CODE(dali_dbg_printf printfargs ;)}
#define DALI_DBG_CLEANUP_ST_PRINTF(printfargs) \
        { DALI_DBG_CLEANUP_ST_CODE( dali_dbg_printf printfargs ;)}
#define DALI_DBG_CLEANUP_VAR(decl)  decl
#define DALI_DBG_CLEANUP(printfargs) DALI_DBG_CLEANUP_ST_PRINTF(printfargs)
#else
#define DALI_DBG_CLEANUP_CODE(stmt)   ;
#define DALI_DBG_CLEANUP_ST_CODE(stmt)   ;
#define DALI_DBG_CLEANUP_PRINTF(printfargs)   ;
#define DALI_DBG_CLEANUP_ST_PRINTF(printfargs)   ;
#define DALI_DBG_CLEANUP_VAR(decl)   
#define DALI_DBG_CLEANUP(printfargs) ;

#endif

/*
 * DALI_DBG_CLEANUP1:
 *      Process failure cleanup code -- more detai
 */
#if  !defined(NO_DALI_DBG_CLEANUP1) && !defined(NO_DALI_DBG)
extern int dali_dbg_cleanup1;
#define DALI_DBG_CLEANUP1_CODE(stmt)  {if(dali_dbg_cleanup1) {stmt}}
#define DALI_DBG_CLEANUP1_ST_CODE(stmt)  {if(dali_dbg_cleanup1) { \
        dali_dbg_stamp( 20, __FILE__, __LINE__); {stmt} }}
#define DALI_DBG_CLEANUP1_PRINTF(printfargs) \
        { DALI_DBG_CLEANUP1_CODE(dali_dbg_printf printfargs ;)}
#define DALI_DBG_CLEANUP1_ST_PRINTF(printfargs) \
        { DALI_DBG_CLEANUP1_ST_CODE( dali_dbg_printf printfargs ;)}
#define DALI_DBG_CLEANUP1_VAR(decl)  decl
#define DALI_DBG_CLEANUP1(printfargs) DALI_DBG_CLEANUP1_ST_PRINTF(printfargs)
#else
#define DALI_DBG_CLEANUP1_CODE(stmt)   ;
#define DALI_DBG_CLEANUP1_ST_CODE(stmt)   ;
#define DALI_DBG_CLEANUP1_PRINTF(printfargs)   ;
#define DALI_DBG_CLEANUP1_ST_PRINTF(printfargs)   ;
#define DALI_DBG_CLEANUP1_VAR(decl)   
#define DALI_DBG_CLEANUP1(printfargs) ;

#endif

/*
 * DALI_DBG_NOEXITCODE:
 *      Turns off exit processing -- if abort doesn't go to debugger
 */
#if  !defined(NO_DALI_DBG_NOEXITCODE) && !defined(NO_DALI_DBG)
extern int dali_dbg_noexitcode;
#define DALI_DBG_NOEXITCODE_CODE(stmt)  {if(dali_dbg_noexitcode) {stmt}}
#define DALI_DBG_NOEXITCODE_ST_CODE(stmt)  {if(dali_dbg_noexitcode) { \
        dali_dbg_stamp( 21, __FILE__, __LINE__); {stmt} }}
#define DALI_DBG_NOEXITCODE_PRINTF(printfargs) \
        { DALI_DBG_NOEXITCODE_CODE(dali_dbg_printf printfargs ;)}
#define DALI_DBG_NOEXITCODE_ST_PRINTF(printfargs) \
        { DALI_DBG_NOEXITCODE_ST_CODE( dali_dbg_printf printfargs ;)}
#define DALI_DBG_NOEXITCODE_VAR(decl)  decl
#define DALI_DBG_NOEXITCODE(printfargs) DALI_DBG_NOEXITCODE_ST_PRINTF(printfargs)
#else
#define DALI_DBG_NOEXITCODE_CODE(stmt)   ;
#define DALI_DBG_NOEXITCODE_ST_CODE(stmt)   ;
#define DALI_DBG_NOEXITCODE_PRINTF(printfargs)   ;
#define DALI_DBG_NOEXITCODE_ST_PRINTF(printfargs)   ;
#define DALI_DBG_NOEXITCODE_VAR(decl)   
#define DALI_DBG_NOEXITCODE(printfargs) ;

#endif

/*
 * DALI_DBG_CODEWORD:
 *      Code word audit
 */
#if  !defined(NO_DALI_DBG_CODEWORD) && !defined(NO_DALI_DBG)
extern int dali_dbg_codeword;
#define DALI_DBG_CODEWORD_CODE(stmt)  {if(dali_dbg_codeword) {stmt}}
#define DALI_DBG_CODEWORD_ST_CODE(stmt)  {if(dali_dbg_codeword) { \
        dali_dbg_stamp( 22, __FILE__, __LINE__); {stmt} }}
#define DALI_DBG_CODEWORD_PRINTF(printfargs) \
        { DALI_DBG_CODEWORD_CODE(dali_dbg_printf printfargs ;)}
#define DALI_DBG_CODEWORD_ST_PRINTF(printfargs) \
        { DALI_DBG_CODEWORD_ST_CODE( dali_dbg_printf printfargs ;)}
#define DALI_DBG_CODEWORD_VAR(decl)  decl
#define DALI_DBG_CODEWORD(printfargs) DALI_DBG_CODEWORD_ST_PRINTF(printfargs)
#else
#define DALI_DBG_CODEWORD_CODE(stmt)   ;
#define DALI_DBG_CODEWORD_ST_CODE(stmt)   ;
#define DALI_DBG_CODEWORD_PRINTF(printfargs)   ;
#define DALI_DBG_CODEWORD_ST_PRINTF(printfargs)   ;
#define DALI_DBG_CODEWORD_VAR(decl)   
#define DALI_DBG_CODEWORD(printfargs) ;

#endif

/*
 * DALI_DBG_CHECKPT:
 *      Checkpoint server and checkpointing -- less detai
 */
#if  !defined(NO_DALI_DBG_CHECKPT) && !defined(NO_DALI_DBG)
extern int dali_dbg_checkpt;
#define DALI_DBG_CHECKPT_CODE(stmt)  {if(dali_dbg_checkpt) {stmt}}
#define DALI_DBG_CHECKPT_ST_CODE(stmt)  {if(dali_dbg_checkpt) { \
        dali_dbg_stamp( 23, __FILE__, __LINE__); {stmt} }}
#define DALI_DBG_CHECKPT_PRINTF(printfargs) \
        { DALI_DBG_CHECKPT_CODE(dali_dbg_printf printfargs ;)}
#define DALI_DBG_CHECKPT_ST_PRINTF(printfargs) \
        { DALI_DBG_CHECKPT_ST_CODE( dali_dbg_printf printfargs ;)}
#define DALI_DBG_CHECKPT_VAR(decl)  decl
#define DALI_DBG_CHECKPT(printfargs) DALI_DBG_CHECKPT_ST_PRINTF(printfargs)
#else
#define DALI_DBG_CHECKPT_CODE(stmt)   ;
#define DALI_DBG_CHECKPT_ST_CODE(stmt)   ;
#define DALI_DBG_CHECKPT_PRINTF(printfargs)   ;
#define DALI_DBG_CHECKPT_ST_PRINTF(printfargs)   ;
#define DALI_DBG_CHECKPT_VAR(decl)   
#define DALI_DBG_CHECKPT(printfargs) ;

#endif

/*
 * DALI_DBG_CHECKPT1:
 *      Checkpoint server and checkpointing -- more detai
 */
#if  !defined(NO_DALI_DBG_CHECKPT1) && !defined(NO_DALI_DBG)
extern int dali_dbg_checkpt1;
#define DALI_DBG_CHECKPT1_CODE(stmt)  {if(dali_dbg_checkpt1) {stmt}}
#define DALI_DBG_CHECKPT1_ST_CODE(stmt)  {if(dali_dbg_checkpt1) { \
        dali_dbg_stamp( 24, __FILE__, __LINE__); {stmt} }}
#define DALI_DBG_CHECKPT1_PRINTF(printfargs) \
        { DALI_DBG_CHECKPT1_CODE(dali_dbg_printf printfargs ;)}
#define DALI_DBG_CHECKPT1_ST_PRINTF(printfargs) \
        { DALI_DBG_CHECKPT1_ST_CODE( dali_dbg_printf printfargs ;)}
#define DALI_DBG_CHECKPT1_VAR(decl)  decl
#define DALI_DBG_CHECKPT1(printfargs) DALI_DBG_CHECKPT1_ST_PRINTF(printfargs)
#else
#define DALI_DBG_CHECKPT1_CODE(stmt)   ;
#define DALI_DBG_CHECKPT1_ST_CODE(stmt)   ;
#define DALI_DBG_CHECKPT1_PRINTF(printfargs)   ;
#define DALI_DBG_CHECKPT1_ST_PRINTF(printfargs)   ;
#define DALI_DBG_CHECKPT1_VAR(decl)   
#define DALI_DBG_CHECKPT1(printfargs) ;

#endif

/*
 * DALI_DBG_ROOTSRV:
 *      Root serve
 */
#if  !defined(NO_DALI_DBG_ROOTSRV) && !defined(NO_DALI_DBG)
extern int dali_dbg_rootsrv;
#define DALI_DBG_ROOTSRV_CODE(stmt)  {if(dali_dbg_rootsrv) {stmt}}
#define DALI_DBG_ROOTSRV_ST_CODE(stmt)  {if(dali_dbg_rootsrv) { \
        dali_dbg_stamp( 25, __FILE__, __LINE__); {stmt} }}
#define DALI_DBG_ROOTSRV_PRINTF(printfargs) \
        { DALI_DBG_ROOTSRV_CODE(dali_dbg_printf printfargs ;)}
#define DALI_DBG_ROOTSRV_ST_PRINTF(printfargs) \
        { DALI_DBG_ROOTSRV_ST_CODE( dali_dbg_printf printfargs ;)}
#define DALI_DBG_ROOTSRV_VAR(decl)  decl
#define DALI_DBG_ROOTSRV(printfargs) DALI_DBG_ROOTSRV_ST_PRINTF(printfargs)
#else
#define DALI_DBG_ROOTSRV_CODE(stmt)   ;
#define DALI_DBG_ROOTSRV_ST_CODE(stmt)   ;
#define DALI_DBG_ROOTSRV_PRINTF(printfargs)   ;
#define DALI_DBG_ROOTSRV_ST_PRINTF(printfargs)   ;
#define DALI_DBG_ROOTSRV_VAR(decl)   
#define DALI_DBG_ROOTSRV(printfargs) ;

#endif

/*
 * DALI_DBG_ROOTSRV_DBX:
 *      Allow using DBX to debug servers started from root server
 */
#if  !defined(NO_DALI_DBG_ROOTSRV_DBX) && !defined(NO_DALI_DBG)
extern int dali_dbg_rootsrv_dbx;
#define DALI_DBG_ROOTSRV_DBX_CODE(stmt)  {if(dali_dbg_rootsrv_dbx) {stmt}}
#define DALI_DBG_ROOTSRV_DBX_ST_CODE(stmt)  {if(dali_dbg_rootsrv_dbx) { \
        dali_dbg_stamp( 26, __FILE__, __LINE__); {stmt} }}
#define DALI_DBG_ROOTSRV_DBX_PRINTF(printfargs) \
        { DALI_DBG_ROOTSRV_DBX_CODE(dali_dbg_printf printfargs ;)}
#define DALI_DBG_ROOTSRV_DBX_ST_PRINTF(printfargs) \
        { DALI_DBG_ROOTSRV_DBX_ST_CODE( dali_dbg_printf printfargs ;)}
#define DALI_DBG_ROOTSRV_DBX_VAR(decl)  decl
#define DALI_DBG_ROOTSRV_DBX(printfargs) DALI_DBG_ROOTSRV_DBX_ST_PRINTF(printfargs)
#else
#define DALI_DBG_ROOTSRV_DBX_CODE(stmt)   ;
#define DALI_DBG_ROOTSRV_DBX_ST_CODE(stmt)   ;
#define DALI_DBG_ROOTSRV_DBX_PRINTF(printfargs)   ;
#define DALI_DBG_ROOTSRV_DBX_ST_PRINTF(printfargs)   ;
#define DALI_DBG_ROOTSRV_DBX_VAR(decl)   
#define DALI_DBG_ROOTSRV_DBX(printfargs) ;

#endif

/*
 * DALI_DBG_EXTERNAL_LOCK_AUDIT:
 *      dump lock actions to file for external audit (not impl
 */
#if  !defined(NO_DALI_DBG_EXTERNAL_LOCK_AUDIT) && !defined(NO_DALI_DBG)
extern int dali_dbg_external_lock_audit;
#define DALI_DBG_EXTERNAL_LOCK_AUDIT_CODE(stmt)  {if(dali_dbg_external_lock_audit) {stmt}}
#define DALI_DBG_EXTERNAL_LOCK_AUDIT_ST_CODE(stmt)  {if(dali_dbg_external_lock_audit) { \
        dali_dbg_stamp( 27, __FILE__, __LINE__); {stmt} }}
#define DALI_DBG_EXTERNAL_LOCK_AUDIT_PRINTF(printfargs) \
        { DALI_DBG_EXTERNAL_LOCK_AUDIT_CODE(dali_dbg_printf printfargs ;)}
#define DALI_DBG_EXTERNAL_LOCK_AUDIT_ST_PRINTF(printfargs) \
        { DALI_DBG_EXTERNAL_LOCK_AUDIT_ST_CODE( dali_dbg_printf printfargs ;)}
#define DALI_DBG_EXTERNAL_LOCK_AUDIT_VAR(decl)  decl
#define DALI_DBG_EXTERNAL_LOCK_AUDIT(printfargs) DALI_DBG_EXTERNAL_LOCK_AUDIT_ST_PRINTF(printfargs)
#else
#define DALI_DBG_EXTERNAL_LOCK_AUDIT_CODE(stmt)   ;
#define DALI_DBG_EXTERNAL_LOCK_AUDIT_ST_CODE(stmt)   ;
#define DALI_DBG_EXTERNAL_LOCK_AUDIT_PRINTF(printfargs)   ;
#define DALI_DBG_EXTERNAL_LOCK_AUDIT_ST_PRINTF(printfargs)   ;
#define DALI_DBG_EXTERNAL_LOCK_AUDIT_VAR(decl)   
#define DALI_DBG_EXTERNAL_LOCK_AUDIT(printfargs) ;

#endif

/*
 * DALI_DBG_EXTERNAL_ALLOC_AUDIT:
 *      dump alloc actions to file for external audi
 */
#if  !defined(NO_DALI_DBG_EXTERNAL_ALLOC_AUDIT) && !defined(NO_DALI_DBG)
extern int dali_dbg_external_alloc_audit;
#define DALI_DBG_EXTERNAL_ALLOC_AUDIT_CODE(stmt)  {if(dali_dbg_external_alloc_audit) {stmt}}
#define DALI_DBG_EXTERNAL_ALLOC_AUDIT_ST_CODE(stmt)  {if(dali_dbg_external_alloc_audit) { \
        dali_dbg_stamp( 28, __FILE__, __LINE__); {stmt} }}
#define DALI_DBG_EXTERNAL_ALLOC_AUDIT_PRINTF(printfargs) \
        { DALI_DBG_EXTERNAL_ALLOC_AUDIT_CODE(dali_dbg_printf printfargs ;)}
#define DALI_DBG_EXTERNAL_ALLOC_AUDIT_ST_PRINTF(printfargs) \
        { DALI_DBG_EXTERNAL_ALLOC_AUDIT_ST_CODE( dali_dbg_printf printfargs ;)}
#define DALI_DBG_EXTERNAL_ALLOC_AUDIT_VAR(decl)  decl
#define DALI_DBG_EXTERNAL_ALLOC_AUDIT(printfargs) DALI_DBG_EXTERNAL_ALLOC_AUDIT_ST_PRINTF(printfargs)
#else
#define DALI_DBG_EXTERNAL_ALLOC_AUDIT_CODE(stmt)   ;
#define DALI_DBG_EXTERNAL_ALLOC_AUDIT_ST_CODE(stmt)   ;
#define DALI_DBG_EXTERNAL_ALLOC_AUDIT_PRINTF(printfargs)   ;
#define DALI_DBG_EXTERNAL_ALLOC_AUDIT_ST_PRINTF(printfargs)   ;
#define DALI_DBG_EXTERNAL_ALLOC_AUDIT_VAR(decl)   
#define DALI_DBG_EXTERNAL_ALLOC_AUDIT(printfargs) ;

#endif

/*
 * DALI_DBG_PAGE_TABLE:
 *      Debug PageTable creation and setting entries
 */
#if  !defined(NO_DALI_DBG_PAGE_TABLE) && !defined(NO_DALI_DBG)
extern int dali_dbg_page_table;
#define DALI_DBG_PAGE_TABLE_CODE(stmt)  {if(dali_dbg_page_table) {stmt}}
#define DALI_DBG_PAGE_TABLE_ST_CODE(stmt)  {if(dali_dbg_page_table) { \
        dali_dbg_stamp( 29, __FILE__, __LINE__); {stmt} }}
#define DALI_DBG_PAGE_TABLE_PRINTF(printfargs) \
        { DALI_DBG_PAGE_TABLE_CODE(dali_dbg_printf printfargs ;)}
#define DALI_DBG_PAGE_TABLE_ST_PRINTF(printfargs) \
        { DALI_DBG_PAGE_TABLE_ST_CODE( dali_dbg_printf printfargs ;)}
#define DALI_DBG_PAGE_TABLE_VAR(decl)  decl
#define DALI_DBG_PAGE_TABLE(printfargs) DALI_DBG_PAGE_TABLE_ST_PRINTF(printfargs)
#else
#define DALI_DBG_PAGE_TABLE_CODE(stmt)   ;
#define DALI_DBG_PAGE_TABLE_ST_CODE(stmt)   ;
#define DALI_DBG_PAGE_TABLE_PRINTF(printfargs)   ;
#define DALI_DBG_PAGE_TABLE_ST_PRINTF(printfargs)   ;
#define DALI_DBG_PAGE_TABLE_VAR(decl)   
#define DALI_DBG_PAGE_TABLE(printfargs) ;

#endif

/*
 * DALI_DBG_TTREE:
 *      ttree cod
 */
#if  !defined(NO_DALI_DBG_TTREE) && !defined(NO_DALI_DBG)
extern int dali_dbg_ttree;
#define DALI_DBG_TTREE_CODE(stmt)  {if(dali_dbg_ttree) {stmt}}
#define DALI_DBG_TTREE_ST_CODE(stmt)  {if(dali_dbg_ttree) { \
        dali_dbg_stamp( 30, __FILE__, __LINE__); {stmt} }}
#define DALI_DBG_TTREE_PRINTF(printfargs) \
        { DALI_DBG_TTREE_CODE(dali_dbg_printf printfargs ;)}
#define DALI_DBG_TTREE_ST_PRINTF(printfargs) \
        { DALI_DBG_TTREE_ST_CODE( dali_dbg_printf printfargs ;)}
#define DALI_DBG_TTREE_VAR(decl)  decl
#define DALI_DBG_TTREE(printfargs) DALI_DBG_TTREE_ST_PRINTF(printfargs)
#else
#define DALI_DBG_TTREE_CODE(stmt)   ;
#define DALI_DBG_TTREE_ST_CODE(stmt)   ;
#define DALI_DBG_TTREE_PRINTF(printfargs)   ;
#define DALI_DBG_TTREE_ST_PRINTF(printfargs)   ;
#define DALI_DBG_TTREE_VAR(decl)   
#define DALI_DBG_TTREE(printfargs) ;

#endif

/*
 * DALI_DBG_TTREE1:
 *      ttree more inf
 */
#if  !defined(NO_DALI_DBG_TTREE1) && !defined(NO_DALI_DBG)
extern int dali_dbg_ttree1;
#define DALI_DBG_TTREE1_CODE(stmt)  {if(dali_dbg_ttree1) {stmt}}
#define DALI_DBG_TTREE1_ST_CODE(stmt)  {if(dali_dbg_ttree1) { \
        dali_dbg_stamp( 31, __FILE__, __LINE__); {stmt} }}
#define DALI_DBG_TTREE1_PRINTF(printfargs) \
        { DALI_DBG_TTREE1_CODE(dali_dbg_printf printfargs ;)}
#define DALI_DBG_TTREE1_ST_PRINTF(printfargs) \
        { DALI_DBG_TTREE1_ST_CODE( dali_dbg_printf printfargs ;)}
#define DALI_DBG_TTREE1_VAR(decl)  decl
#define DALI_DBG_TTREE1(printfargs) DALI_DBG_TTREE1_ST_PRINTF(printfargs)
#else
#define DALI_DBG_TTREE1_CODE(stmt)   ;
#define DALI_DBG_TTREE1_ST_CODE(stmt)   ;
#define DALI_DBG_TTREE1_PRINTF(printfargs)   ;
#define DALI_DBG_TTREE1_ST_PRINTF(printfargs)   ;
#define DALI_DBG_TTREE1_VAR(decl)   
#define DALI_DBG_TTREE1(printfargs) ;

#endif

/*
 * DALI_DBG_HASH:
 *      hash cod
 */
#if  !defined(NO_DALI_DBG_HASH) && !defined(NO_DALI_DBG)
extern int dali_dbg_hash;
#define DALI_DBG_HASH_CODE(stmt)  {if(dali_dbg_hash) {stmt}}
#define DALI_DBG_HASH_ST_CODE(stmt)  {if(dali_dbg_hash) { \
        dali_dbg_stamp( 32, __FILE__, __LINE__); {stmt} }}
#define DALI_DBG_HASH_PRINTF(printfargs) \
        { DALI_DBG_HASH_CODE(dali_dbg_printf printfargs ;)}
#define DALI_DBG_HASH_ST_PRINTF(printfargs) \
        { DALI_DBG_HASH_ST_CODE( dali_dbg_printf printfargs ;)}
#define DALI_DBG_HASH_VAR(decl)  decl
#define DALI_DBG_HASH(printfargs) DALI_DBG_HASH_ST_PRINTF(printfargs)
#else
#define DALI_DBG_HASH_CODE(stmt)   ;
#define DALI_DBG_HASH_ST_CODE(stmt)   ;
#define DALI_DBG_HASH_PRINTF(printfargs)   ;
#define DALI_DBG_HASH_ST_PRINTF(printfargs)   ;
#define DALI_DBG_HASH_VAR(decl)   
#define DALI_DBG_HASH(printfargs) ;

#endif

/*
 * DALI_DBG_SHMEM:
 *      dump shared memory operational informatio
 */
#if  !defined(NO_DALI_DBG_SHMEM) && !defined(NO_DALI_DBG)
extern int dali_dbg_shmem;
#define DALI_DBG_SHMEM_CODE(stmt)  {if(dali_dbg_shmem) {stmt}}
#define DALI_DBG_SHMEM_ST_CODE(stmt)  {if(dali_dbg_shmem) { \
        dali_dbg_stamp( 33, __FILE__, __LINE__); {stmt} }}
#define DALI_DBG_SHMEM_PRINTF(printfargs) \
        { DALI_DBG_SHMEM_CODE(dali_dbg_printf printfargs ;)}
#define DALI_DBG_SHMEM_ST_PRINTF(printfargs) \
        { DALI_DBG_SHMEM_ST_CODE( dali_dbg_printf printfargs ;)}
#define DALI_DBG_SHMEM_VAR(decl)  decl
#define DALI_DBG_SHMEM(printfargs) DALI_DBG_SHMEM_ST_PRINTF(printfargs)
#else
#define DALI_DBG_SHMEM_CODE(stmt)   ;
#define DALI_DBG_SHMEM_ST_CODE(stmt)   ;
#define DALI_DBG_SHMEM_PRINTF(printfargs)   ;
#define DALI_DBG_SHMEM_ST_PRINTF(printfargs)   ;
#define DALI_DBG_SHMEM_VAR(decl)   
#define DALI_DBG_SHMEM(printfargs) ;

#endif

#endif
